version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 5000:80
    environment:
      PORT: "80"
      DATABASE_URL: mongodb://mongodb
    volumes:
      - ./:/app

  mongodb:
    image : mongo
    restart: on-failure
    environment:
      - MONGO_INITDB_DATABASE=dockwork
      - MONGO_REPLICA_SET_NAME=rs0
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 30s
      start_period: 10s
    command: "--bind_ip_all --replSet rs0"
