type ImageInfo {
    id: ID!
    name: String!
    nodes: [ImageInfoNode!]

    createdAt: Time!
    updatedAt: Time!
    deletedAt: Time
}

type ImageInfoNode {
    name: String!
    namespace: String!
}

input ImageInput {
    name: String!
    node: ImageNodeInput!
}

input ImageNodeInput {
    name: String!
    namespace: String!
}

extend type Query {
    images(last: Int, skip: Int): [ImageInfo!]
    image(name: String!): ImageInfo!
}

extend type Mutation {
    addImage(image: ImageInput!): ImageInfo!
    deleteImage(name: String!): ImageInfo!
    deleteImages(names: [String!]!): [ImageInfo!]
    deletedNodeImage(imageName: String!, node: ImageNodeInput!): ImageInfo!
}

extend type Subscription {
    deleteImageNotification(node: String): ImageInfo!
}
